//! Data compatibility testing between the current `zarrs` and previous releases.
//!
//! Arrays are written and read with the current `zarrs` and with previous releases (via helper binaries), for every combination of codec and data type.
//! Codec parameters, shapes and data are sampled with proptest.
//!
//! By default, only the latest release is tested and any regression results in a non-zero exit code.
//! With `--all`, every release is tested and a summary of how far back compatibility extends is printed.
//! With `--json <PATH>`, the cases and results are written as JSON (see [`zarrs_regression_testing::schema`]).
//! HTML reports of the results (e.g. for zarrs.dev) are generated by [`zarr_compatibility`](https://github.com/zarrs/zarr_compatibility).
//!
//! Subcommands make `zarrs` available to other tools (see `PROTOCOL.md`): `cases` writes the cases without running them, `serve` serves the helper protocol with the current `zarrs` or a release, and `build` builds release helpers.

#[cfg(target_endian = "big")]
compile_error!("array data is exchanged as native-endian bytes, but must be little-endian");

mod cases;
mod conformance;
mod data;
mod export;
mod format;
mod helper;
mod introduced;
mod native;
mod releases;
mod run;
mod serve;
mod summary;

use std::fmt::Write as _;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::Parser;

use zarrs_regression_testing::schema;

use crate::releases::RELEASES;

/// Test data compatibility between the current zarrs and previous releases.
#[derive(Parser)]
#[command(args_conflicts_with_subcommands = true)]
struct Args {
    #[command(subcommand)]
    command: Option<Command>,
    #[command(flatten)]
    cases: CaseArgs,
    /// Test all previous releases and summarise how far back compatibility extends.
    ///
    /// By default, only the latest release is tested.
    #[arg(long)]
    all: bool,
    /// Print every failure rather than one per combination.
    #[arg(long, short)]
    verbose: bool,
    /// Write the cases and results as JSON (see `zarrs_regression_testing::schema::Results`).
    #[arg(long, value_name = "PATH")]
    json: Option<PathBuf>,
}

/// The sampling of cases.
#[derive(clap::Args)]
struct CaseArgs {
    /// The number of samples of each codec/data type combination.
    #[arg(long, default_value_t = 2)]
    samples: usize,
    /// The seed for sampling cases (random by default).
    #[arg(long)]
    seed: Option<u64>,
    /// Only test combinations whose codec or data type contains this string.
    #[arg(long)]
    filter: Option<String>,
}

#[derive(clap::Subcommand)]
enum Command {
    /// Write the cases as JSON (see `zarrs_regression_testing::schema::Manifest`) without running them.
    Cases {
        #[command(flatten)]
        cases: CaseArgs,
        /// The path to write the cases to (stdout by default).
        #[arg(long, value_name = "PATH")]
        out: Option<PathBuf>,
    },
    /// Serve the helper protocol (see `zarrs_regression_testing::schema::Request`) on stdin/stdout with a zarrs.
    ///
    /// The helper of a release is built if needed, so build helpers first (see `build`) before serving a release concurrently.
    Serve {
        /// `current` or a tested release (e.g. `0.23`).
        #[arg(long)]
        zarrs: serve::Zarrs,
    },
    /// Build the helpers of releases (all tested releases by default).
    Build {
        /// Tested releases (e.g. `0.23`).
        releases: Vec<releases::Release>,
    },
}

fn main() -> ExitCode {
    let args = Args::parse();
    let result = match &args.command {
        None => run(&args),
        Some(Command::Cases { cases, out }) => write_cases(cases, out.as_deref()).map(|()| true),
        Some(Command::Serve { zarrs }) => serve::serve(*zarrs).map(|()| true),
        Some(Command::Build { releases }) => build(releases).map(|()| true),
    };
    match result {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::FAILURE,
        Err(err) => {
            eprintln!("error: {err}");
            ExitCode::FAILURE
        }
    }
}

/// Cases sampled with a seed.
struct Sample {
    seed: u64,
    data_types: Vec<cases::DataTypeCase>,
    combinations: Vec<cases::Combination>,
    cases: Vec<cases::Case>,
}

/// Sample cases with `args`.
fn sample(args: &CaseArgs) -> Result<Sample, String> {
    let seed = args.seed.unwrap_or_else(|| {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |duration| {
                duration.as_secs() ^ u64::from(duration.subsec_nanos())
            })
    });
    let data_types = cases::data_types();
    let combinations: Vec<_> = cases::combinations(&cases::codec_kinds(), &data_types)
        .into_iter()
        .filter(|combination| {
            args.filter.as_ref().is_none_or(|filter| {
                combination.codec.to_string().contains(filter)
                    || data_types[combination.data_type].label.contains(filter)
            })
        })
        .collect();
    let cases = cases::sample_cases(&combinations, &data_types, args.samples, seed)?;
    Ok(Sample {
        seed,
        data_types,
        combinations,
        cases,
    })
}

/// Write the cases sampled with `args` to `out` (or stdout).
fn write_cases(args: &CaseArgs, out: Option<&std::path::Path>) -> Result<(), String> {
    let Sample {
        seed,
        data_types,
        combinations,
        cases,
    } = sample(args)?;
    let meta = schema_meta(args, seed, reproduce("cases ", args, seed, false));
    let manifest = export::manifest(meta, &data_types, &combinations, &cases);
    let json = serde_json::to_string(&manifest).map_err(|err| format!("serialise cases: {err}"))?;
    if let Some(path) = out {
        std::fs::write(path, json).map_err(|err| format!("write {}: {err}", path.display()))
    } else {
        println!("{json}");
        Ok(())
    }
}

/// Build the helpers of `releases` (or all tested releases).
fn build(releases: &[releases::Release]) -> Result<(), String> {
    let releases = if releases.is_empty() {
        RELEASES
    } else {
        releases
    };
    for &release in releases {
        let binary = helper::build(release)?;
        println!("{release}: {}", binary.display());
    }
    Ok(())
}

/// Returns `true` if there are no failures with the latest release.
fn run(args: &Args) -> Result<bool, String> {
    let Sample {
        seed,
        data_types,
        combinations,
        cases,
    } = sample(&args.cases)?;
    let latest = RELEASES[0];
    let releases = if args.all { RELEASES } else { &RELEASES[..1] };

    let work_dir = helper::root_dir()
        .join("work")
        .join(if args.all { "all" } else { "latest" });
    let results = run::run(&cases, &combinations, &data_types, releases, &work_dir)?;

    let run = summary::Run {
        data_types: &data_types,
        combinations: &combinations,
        cases: &cases,
        results: &results,
        releases,
        work_dir: &work_dir,
    };
    let (failures, known_issues) = run.failures();
    let latest_failures: Vec<_> = failures
        .iter()
        .filter(|failure| failure.release.is_none_or(|release| release == latest))
        .collect();

    println!(
        "zarrs regression testing: current zarrs vs {}",
        if args.all {
            format!("releases {}–{latest}", releases[releases.len() - 1])
        } else {
            format!("latest release {latest}")
        }
    );
    println!(
        "{} combinations × {} samples = {} cases (--seed {seed})\n",
        combinations.len(),
        args.cases.samples,
        cases.len()
    );
    print_releases(&run, &failures, args);

    if !known_issues.is_empty() {
        let known_issues: Vec<_> = known_issues.iter().collect();
        println!(
            "Known issues (current and {latest} cannot read back data they wrote, or a release rejects conformant data as it writes non-conformant data):"
        );
        print!("{}", format_failures(&run, &known_issues, args.verbose));
        println!();
    }

    println!("{}", run.counts());
    if latest_failures.is_empty() {
        println!("✓ no regressions: current zarrs and zarrs {latest} read each other's data");
    } else {
        println!("Regressions with the latest release ({latest}):");
        print!("{}", run.format_failures(&latest_failures, args.verbose));
        println!("\n✗ {} failing cases", latest_failures.len());
    }

    if let Some(path) = &args.json {
        write_json(path, args, seed, &run)?;
    }
    Ok(latest_failures.is_empty())
}

/// Write the cases and results as JSON to `path`.
fn write_json(
    path: &std::path::Path,
    args: &Args,
    seed: u64,
    run: &summary::Run,
) -> Result<(), String> {
    let manifest = export::manifest(
        schema_meta(
            &args.cases,
            seed,
            reproduce("", &args.cases, seed, args.all),
        ),
        run.data_types,
        run.combinations,
        run.cases,
    );
    let results = export::results(manifest, run);
    let json =
        serde_json::to_string(&results).map_err(|err| format!("serialise results: {err}"))?;
    std::fs::write(path, json).map_err(|err| format!("write {}: {err}", path.display()))?;
    println!("results written to {}", path.display());
    Ok(())
}

/// A command that reproduces a run (or a `subcommand`, e.g. `cases `) with `args`, `seed` and `--all` if `all`.
fn reproduce(subcommand: &str, args: &CaseArgs, seed: u64, all: bool) -> String {
    let mut reproduce = format!(
        "cargo run -p zarrs_regression_testing -- {subcommand}--seed {seed} --samples {}",
        args.samples
    );
    if all {
        reproduce.push_str(" --all");
    }
    if let Some(filter) = &args.filter {
        let _ = write!(reproduce, " --filter '{filter}'");
    }
    reproduce
}

/// The parameters of a run for the machine-readable interface.
fn schema_meta(args: &CaseArgs, seed: u64, reproduce: String) -> schema::Meta {
    let commit = commit();
    schema::Meta {
        generator: schema::Generator {
            name: env!("CARGO_PKG_NAME").to_string(),
            version: env!("CARGO_PKG_VERSION").to_string(),
            repository: env!("CARGO_PKG_REPOSITORY").to_string(),
            modified: commit.as_ref().is_some_and(|&(_, modified)| modified),
            commit: commit.map(|(commit, _)| commit),
        },
        date: date(std::time::SystemTime::now()),
        seed,
        samples: args.samples,
        filter: args.filter.clone(),
        reproduce,
    }
}

/// The commit of the workspace, and whether it has changes not committed outside of tests (if it is a git repository).
fn commit() -> Option<(String, bool)> {
    let git = |args: &[&str]| {
        std::process::Command::new("git")
            .arg("-C")
            .arg(env!("CARGO_MANIFEST_DIR"))
            .args(args)
            .output()
            .ok()
    };
    let output = git(&["rev-parse", "HEAD"]).filter(|output| output.status.success())?;
    let commit = String::from_utf8_lossy(&output.stdout).trim().to_string();
    // Tests modify their data (e.g. `zarrs/tests/data`)
    let modified = git(&[
        "diff",
        "--quiet",
        "HEAD",
        "--",
        ":(top)",
        ":(top,exclude,glob)**/tests/**",
    ])
    .is_some_and(|output| !output.status.success());
    Some((commit, modified))
}

/// The UTC date of `time`, e.g. `2026-10-08`.
fn date(time: std::time::SystemTime) -> String {
    let days = time
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |duration| duration.as_secs() / 86_400);
    // Days to a civil date (http://howardhinnant.github.io/date_algorithms.html#civil_from_days), from 0000-03-01
    let days = days + 719_468;
    let era = days / 146_097;
    let day_of_era = days % 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_index = (5 * day_of_year + 2) / 153; // from March
    let day = day_of_year - (153 * month_index + 2) / 5 + 1;
    let month = if month_index < 10 {
        month_index + 3
    } else {
        month_index - 9
    };
    let year = era * 400 + year_of_era + u64::from(month <= 2);
    format!("{year:04}-{month:02}-{day:02}")
}

/// Format failures with details if `verbose`, otherwise concisely.
fn format_failures(run: &summary::Run, failures: &[&summary::Failure], verbose: bool) -> String {
    if verbose {
        run.format_failures(failures, true)
    } else {
        run.format_failures_concise(failures)
    }
}

/// Print the compatibility with older releases (if testing all releases) and non-conformant data and unregistered names written by releases.
fn print_releases(run: &summary::Run, failures: &[summary::Failure], args: &Args) {
    let latest = run.releases[0];
    if args.all {
        print!("{}", run.compatibility());
        let older_failures: Vec<_> = failures
            .iter()
            .filter(|failure| failure.release.is_some_and(|release| release != latest))
            .collect();
        if !older_failures.is_empty() {
            println!(
                "\nIncompatibilities with older releases that support the combination themselves:"
            );
            print!("{}", format_failures(run, &older_failures, args.verbose));
        }
        println!();
    }

    let non_conformances = run.format_non_conformances();
    if !non_conformances.is_empty() {
        println!(
            "Non-conformant data and unregistered names written by releases (read by current zarrs for backwards compatibility where compatible):"
        );
        println!("{non_conformances}");
    }
}

#[cfg(test)]
mod tests {
    use std::time::{Duration, UNIX_EPOCH};

    use super::date;

    #[test]
    fn dates() {
        let days = |days: u64| UNIX_EPOCH + Duration::from_secs(days * 86_400 + 86_399);
        assert_eq!(date(UNIX_EPOCH), "1970-01-01");
        assert_eq!(date(days(11_016)), "2000-02-29");
        assert_eq!(date(days(11_017)), "2000-03-01");
        assert_eq!(date(days(20_000)), "2024-10-04");
    }
}
