#![allow(missing_docs)]

use std::error::Error;
use std::sync::Arc;

use zarrs::array::Array;
use zarrs_filesystem::FilesystemStore;

/// Test data written by zarr-python's FixedLengthUTF32 dtype (V3)
/// and NumPy's <U / >U dtypes (V2).
///
/// V3: fixed_length_utf32 with length_bytes=16 (4 code points, little-endian bytes codec)
/// V2: <U4 (little-endian) and >U4 (big-endian)
///
/// Generated by zarrs/tests/data/zarr_python_fixed_length_utf32.py

/// Test data: mix of ASCII, emoji, short strings, and empty string
const TEST_DATA: [&str; 5] = ["abc", "🎉", "hi", "te", ""];

#[test]
fn zarr_python_v3_fixed_length_utf32_le() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/fixed_length_utf32_v3_le.zarr",
    )?);
    let array = Array::open(store.clone(), "/")?;
    let subset_all = array.subset_all();

    let elements = array.retrieve_array_subset::<Vec<Vec<char>>>(&subset_all)?;

    for (i, chars) in elements.iter().enumerate() {
        let s: String = chars.iter().collect();
        assert_eq!(&s, &TEST_DATA[i], "element {i} mismatch");
    }
    
    let elements = array.retrieve_array_subset::<Vec<[char; 4]>>(&subset_all)?;
    for (i, chars) in elements.iter().enumerate() {
        let s: String = chars.iter().take_while(|&c| *c != '\0').collect();
        assert_eq!(&s, &TEST_DATA[i], "element {i} mismatch");
    }

    Ok(())
}

#[test]
fn zarr_python_v2_fixed_length_utf32_lt_u4() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/fixed_length_utf32_v2_le.zarr",
    )?);
    let array = Array::open(store.clone(), "/")?;
    let subset_all = array.subset_all();

    let elements = array.retrieve_array_subset::<Vec<Vec<char>>>(&subset_all)?;

    for (i, chars) in elements.iter().enumerate() {
        let s: String = chars.iter().collect();
        assert_eq!(&s, &TEST_DATA[i], "element {i} mismatch");
    }

    Ok(())
}

#[test]
fn zarr_python_v2_fixed_length_utf32_gt_u4() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/fixed_length_utf32_v2_be.zarr",
    )?);
    let array = Array::open(store.clone(), "/")?;
    let subset_all = array.subset_all();

    let elements = array.retrieve_array_subset::<Vec<Vec<char>>>(&subset_all)?;

    for (i, chars) in elements.iter().enumerate() {
        let s: String = chars.iter().collect();
        assert_eq!(&s, &TEST_DATA[i], "element {i} mismatch");
    }

    Ok(())
}
