#![allow(missing_docs)]

use std::error::Error;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use serde::Deserialize;
use zarrs::array::{Array, ArrayBytes, ArraySubset};
use zarrs_filesystem::FilesystemStore;

#[cfg(feature = "fletcher32")]
#[test]
fn zarr_python_compat_fletcher32_v2() -> Result<(), Box<dyn Error>> {
    // NOTE: could support numcodecs.zarr3.fletcher32, but would need to permit and ignore "id" field
    // zarrs::config::global_config_mut()
    //     .experimental_codec_names_mut()
    //     .entry("fletcher32".to_string())
    //     .and_modify(|e| *e = "numcodecs.fletcher32".to_string());

    let path = PathBuf::from("tests/data/zarr_python_compat/fletcher32.zarr");
    let store = Arc::new(FilesystemStore::new(&path)?);

    let array = Array::open(store, "/")?;
    assert_eq!(array.shape(), vec![100, 100]);
    let elements = array
        .retrieve_array_subset::<Vec<u16>>(&ArraySubset::new_with_shape(array.shape().to_vec()))?;
    assert_eq!(elements, (0..100 * 100).collect::<Vec<u16>>());

    Ok(())
}

#[cfg(feature = "adler32")]
#[test]
fn zarr_python_compat_adler32_v2() -> Result<(), Box<dyn Error>> {
    // NOTE: could support numcodecs.zarr3.adler32, but would need to permit and ignore "id" field
    // zarrs::config::global_config_mut()
    //     .experimental_codec_names_mut()
    //     .entry("adler32".to_string())
    //     .and_modify(|e| *e = "numcodecs.adler32".to_string());

    let path = PathBuf::from("tests/data/zarr_python_compat/adler32.zarr");
    let store = Arc::new(FilesystemStore::new(&path)?);

    let array = Array::open(store, "/")?;
    assert_eq!(array.shape(), vec![100, 100]);
    let elements = array
        .retrieve_array_subset::<Vec<u16>>(&ArraySubset::new_with_shape(array.shape().to_vec()))?;
    assert_eq!(elements, (0..100 * 100).collect::<Vec<u16>>());

    Ok(())
}

#[test]
fn zarr_python_v2_compat_str_fv_0() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/str_v2_fv_0.zarr",
    )?);
    let array = zarrs::array::Array::open(store.clone(), "/")?;
    let subset_all = array.subset_all();
    let elements = array.retrieve_array_subset::<Vec<String>>(&subset_all)?;

    assert_eq!(elements, &["a", "bb", "", "", ""]);

    Ok(())
}

#[test]
fn zarr_python_v2_compat_str_fv_null() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/str_v2_fv_null.zarr",
    )?);
    let array = zarrs::array::Array::open(store.clone(), "/")?;
    let subset_all = array.subset_all();
    let elements = array.retrieve_array_subset::<Vec<String>>(&subset_all)?;

    assert_eq!(elements, &["a", "bb", "", "", ""]);

    Ok(())
}

#[test]
fn zarr_python_v2_compat_bool_fv_null() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/bool_v2_fv_null.zarr",
    )?);
    let array = Array::open(store, "/")?;
    let subset_all = array.subset_all();
    let elements = array.retrieve_array_subset::<Vec<bool>>(&subset_all)?;
    assert_eq!(elements, &[true, false, false, false, false]);

    Ok(())
}

#[test]
fn zarr_python_v2_compat_int_fv_null() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/int_v2_fv_null.zarr",
    )?);
    let array = Array::open(store, "/")?;
    let subset_all = array.subset_all();
    let elements = array.retrieve_array_subset::<Vec<i32>>(&subset_all)?;
    assert_eq!(elements, &[42, 123, 0, 0, 0]);

    Ok(())
}

#[allow(clippy::approx_constant)]
#[test]
fn zarr_python_v2_compat_float_fv_null() -> Result<(), Box<dyn Error>> {
    let store = Arc::new(FilesystemStore::new(
        "tests/data/zarr_python_compat/float_v2_fv_null.zarr",
    )?);
    let array = Array::open(store, "/")?;
    let subset_all = array.subset_all();
    let elements = array.retrieve_array_subset::<Vec<f32>>(&subset_all)?;
    assert_eq!(elements, &[3.14, 2.71, 0.0, 0.0, 0.0]);

    Ok(())
}

/// Test opening a group with `"consolidated_metadata": null`
/// This is non-conformant and is generated by zarr-python <=3.1.3
/// `zarrs` permits it on read only.
#[test]
fn zarr_python_v3_consolidated_metadata_null() -> Result<(), Box<dyn Error>> {
    use zarrs::group::Group;

    let store = Arc::new(FilesystemStore::new("tests/data/issue_287.zarr")?);
    let group = Group::open(store.clone(), "/")?;

    // Should be able to open the group without errors
    assert_eq!(group.path().as_str(), "/");

    // Should be able to open the meta subgroup
    let meta_group = Group::open(store.clone(), "/meta")?;
    assert_eq!(meta_group.path().as_str(), "/meta");

    Ok(())
}

#[derive(Deserialize)]
struct CastValueMatrixManifest {
    cases: Vec<CastValueMatrixCase>,
}

#[derive(Deserialize)]
struct CastValueMatrixCase {
    source_dtype: String,
    target_dtype: String,
    rounding: String,
    out_of_range: Option<String>,
    path: String,
    expected_decoded_bytes: Vec<u8>,
}

fn zarr_python_uses_nearest_even_for_directed_uint64_to_float(case: &CastValueMatrixCase) -> bool {
    // zarr-python 3.2.1 rounds the decoded `u64::MAX` to the nearest float
    // even when the codec requests a directed mode. The cast_value spec
    // requires the configured rounding mode for this integer-to-float cast.
    case.source_dtype.starts_with("float")
        && case.target_dtype == "uint64"
        && case.out_of_range.as_deref() == Some("wrap")
        && matches!(case.rounding.as_str(), "towards-zero" | "towards-negative")
}

// #[ignore = "requires generated data from tests/data/zarr_python_cast_value_matrix.py"]
#[test]
fn zarr_python_v3_cast_value_matrix_read() -> Result<(), Box<dyn Error>> {
    let root = Path::new("tests/data/zarr_python_compat/cast_value_matrix");
    let manifest_path = root.join("manifest.json");
    if !manifest_path.exists() {
        return Err(format!(
            "missing {}; run `uv run zarrs/tests/data/zarr_python_cast_value_matrix.py` first",
            manifest_path.display()
        )
        .into());
    }

    let manifest: CastValueMatrixManifest =
        serde_json::from_slice(&std::fs::read(&manifest_path)?)?;

    let mut read = 0usize;
    for case in &manifest.cases {
        let path = root.join(&case.path);
        let store = Arc::new(FilesystemStore::new(&path)?);
        let array = Array::open(store, "/")
            .map_err(|err| format!("failed to open {}: {err}", case.path))?;
        let subset_all = array.subset_all();
        let bytes = array
            .retrieve_array_subset::<ArrayBytes<'static>>(&subset_all)
            .map_err(|err| format!("failed to decode {}: {err}", case.path))?;
        let bytes = bytes.into_fixed()?.into_owned();
        if zarr_python_uses_nearest_even_for_directed_uint64_to_float(case) {
            continue;
        }
        assert_eq!(
            bytes,
            case.expected_decoded_bytes.as_slice(),
            "decoded bytes differ for {}",
            case.path
        );
        read += 1;
    }

    assert!(read > 0, "no readable cast_value matrix cases were checked");

    Ok(())
}
